package updatecmd

import (
	"fmt"
	"strings"
)

// scripts.go — V31-001 (VR13-UP): the bash the HOST runs. This file holds what BOTH generated scripts
// share (the literals, the helpers) and preflight.sh; apply.sh is scripts_apply.go, its step bodies
// scripts_steps.go, their compensations scripts_undo.go.
//
// ⛔ NO CREDENTIAL IS EVER RENDERED. `$STAGE` outlives the update and an operator pastes what is in it
// when something goes wrong. Every token the scripts need is read from `env.<id>` BY NAME at run time.
//
// ⛔ AND EVERY OTHER VALUE IS A LITERAL. Not `$ARGUS_KIT_DIR` — the operator's shell may define it
// as something else entirely, which is VR6-S1: a block that acts on whatever happens to be set.
//
// ⭐⭐ THE MECHANISMS ARE THE KIT'S OWN, NOT INVENTED HERE. The first version of these scripts addressed
// `argus-executor-<id>` containers, a `argus-<id>` namespace, `onboarding/lib/k3d.sh`,
// `docker-compose.obs.yml` and a `skills --install` verb — none of which exists. Every test was green,
// because the fixtures were written from the same belief. The scripts now SOURCE the new kit's
// `onboarding/lib/*.sh` and port update.sh / onboard.sh line for line, citing each, and
// kit_layout_test.go derives the names from those scripts rather than restating them.
//
// ⛔ ONE BASH RULE SHAPES EVERY STEP BODY (measured, not assumed): under `set -e` WITHOUT errtrace, a
// command failing INSIDE A FUNCTION exits the script with NO ERR trap — no rollback, no outcome, no
// report. `set -E` is not the cure: it runs the trap inside every failing `$(…)` subshell. So every
// function a step calls passes failure up with `|| return 1`, and is called as `fn || false`, which
// fails at top level where the trap is armed. And `if ! fn` masks a failure in the middle of fn, so
// the undo functions carry `|| return 1` on every effect for the same reason.

const scriptHeader = `#!/usr/bin/env bash
# GENERATED by ` + "`argus update plan`" + ` — do not edit; the next update overwrites it.
#
# Every value below is a literal resolved by the planner. No token value appears in this file: the
# credentials are read from the instance env file BY NAME, at run time, by the lines that need them.
set -euo pipefail
`

// helperUserShell decides, in the generated shell, WHO the update's helper containers run as (AC-D60, #394).
// Only a LINUX host with a NON-ROOT operator gets `--user <uid>:<gid>`: there the standard root Docker daemon
// hands the host root-owned files. Git Bash (uname MINGW*/MSYS*), macOS and a root operator are left exactly as
// they were — a Windows uid names no container user, and Docker Desktop / Rancher Desktop hand files to the host
// user themselves. ONE line, shared by the update block (updatecmd.go) and both generated scripts, so the three
// cannot disagree; every helper `docker run` expands it as ${HELPER_USER:+--user "$HELPER_USER" -e HOME=/tmp}.
//
// ⛔ NOT ON A DAEMON THAT REMAPS UIDS (reviewer, AC-D60). Rootless Docker, a daemon with userns-remap, and Podman
// behind a `docker` shim already map the container's root to the operator — which is why the update works there
// today. `--user <uid>` inside that user namespace lands on a SUBORDINATE uid on the host, so the helpers would
// write files the operator cannot read: the same defect, moved onto the machines it does not affect now. Those
// daemons say so in `docker info` (name=rootless / name=userns) and `docker --version` ("podman").
const helperUserShell = `HELPER_USER=""; if [ "$(uname -s)" = Linux ] && [ "$(id -u)" != 0 ]; then DOCKER_REMAP="$(docker info --format '{{.SecurityOptions}}' 2>/dev/null || true) $(docker --version 2>/dev/null || true)"; case "$DOCKER_REMAP" in *rootless*|*userns*|*odman*) ;; *) HELPER_USER="$(id -u):$(id -g)" ;; esac; fi`

// defaultHealthBudget is update.sh's measured budget (update.sh:662, `healthy 180`).
const defaultHealthBudget = 180

// renderLiterals is the block of values both scripts start from.
//
// ⛔ EVERY PATH IS RENDERED IN ITS MSYS/POSIX SPELLING, and the helper container mounts each one AT
// THAT SAME PATH. That is what lets one literal be right on both sides of C-1: bash on the host opens
// `/c/Users/…`, docker is handed `$(hostpath …)` as the source, and inside the container `update
// rehash --stage /c/Users/…` names the mount. The first version mounted at /kit, /state and /stage and
// then passed the HOST paths as arguments — so every verb it ran inside the container looked for
// directories that were not there.
func renderLiterals(p Plan, in PlanInput) string {
	budget := in.HealthBudget
	if budget <= 0 {
		budget = defaultHealthBudget
	}
	runnerImage := in.RunnerImage
	if runnerImage == "" {
		runnerImage = p.ImageDigest
	}
	from := markerFrom(in)
	var fp Previous
	if from.Previous != nil {
		fp = *from.Previous
	}
	return fmt.Sprintf(`
STAGE=%s
KIT=%s
INSTANCE=%s
ROUTER_STATE=%s
IMAGE_DIGEST=%s
TARGET_VERSION=%s
ROLLBACK_TO=%s
FROM_VERSION=%s
FROM_IMAGE=%s
FROM_PREVIOUS_VERSION=%s
FROM_PREVIOUS_IMAGE=%s
FROM_PREVIOUS_AT=%s
FROM_ONE_OF=%s
RUNNER_IMAGE=%s
GENERATED_AT=%s
TIER=%s
CP_URL=%s
KUBE_CONTEXT=%s
KUBECONFIG_ARG=%s
HEALTH_BUDGET=%d
UPDATE_SCRUB_KEYS=%s
COMPOSE_DIR="$KIT/deploy/compose"
ENV_FILE="$KIT/deploy/compose/env.$INSTANCE"
# the names onboarding gives this instance: onboard.sh:1148 (compose project), update.sh:292-293
PROJECT="argus-inst-$INSTANCE"
NS="argus-inst-$INSTANCE"
`, shq(MSYSPath(in.StageDir)), shq(MSYSPath(in.KitDir)), shq(in.InstanceID), shq(MSYSPath(in.RouterState)),
		shq(p.ImageDigest), shq(p.Version), shq(in.RollbackTo), shq(from.Version), shq(from.Image),
		shq(fp.Version), shq(fp.Image), shq(fp.UpdatedAt), shq(strings.Join(from.OneOf, " ")), shq(runnerImage),
		shq(p.GeneratedAt), shq(in.Tier), shq(in.CPURL), shq(in.KubeContext), shq(in.Kubeconfig), budget,
		shq(strings.Join(EnvScrubKeys(), " "))) + scriptHelpers
}

// markerOrigin is where the executor is BEFORE this update moves it, for the not-confirmed marker (AC-D53).
type markerOrigin struct {
	// Version and Image: what `previous` becomes if the move lands.
	Version, Image string
	// Previous: the `previous` true where the executor is — what `previous` stays if the move does not land.
	Previous *Previous
	// OneOf: when the executor could not be read under an earlier marker, every version that marker left it on — for
	// the downgrade gate (installedForGate).
	OneOf []string
}

// markerFrom is where the executor is before this update moves it. The executor's own reading first (discover asks
// it; the same reading Rehash takes `previous` from); else the record's — but only when no earlier marker stands over
// it, because then the record is stale and the executor may be on either version that marker names. Nothing read:
// "" — never invented.
//
// ⛔ AND THE `previous` TRUE THERE. With no earlier marker it is the record's own — unless discover reads the executor
// on another version than the record's, which makes the record's version where it came from. Under an earlier marker the record
// is stale — the interrupted run could not commit (compose), or committed the executor unknown and kept the old
// previous (k3d) — so the earlier marker is resolved the way the commit resolves it, with the executor where discover
// read it: an earlier forward move that landed is where this executor came from. Taking the record's instead
// recorded a rollback two releases back after the NOTE's own advice, re-running the update. Nothing read under an
// earlier marker: unknown, so none — with one exception, the NOTE's own advice again: a re-run of the SAME move (same
// kind, same target version). Its origin is the earlier move's whichever way that ended: landed, the executor is on
// this target and this run moves nothing; not landed, it is where the earlier move came from. So the earlier move's
// from and the previous true there carry over.
func markerFrom(in PlanInput) markerOrigin {
	e := in.Installed.Unconfirmed
	if v := strings.TrimSpace(in.Observed.ExecutorVersion); v != "" {
		o := markerOrigin{Version: v, Image: observedExecutorImage(in.Observed), Previous: in.Installed.Previous}
		switch {
		case e != nil:
			o.Previous = previousAfterUnconfirmed(e, v, e.At)
		case executorKnown(in.Installed.Version) && in.Installed.Version != v && !sameBinary(in.Installed.Executor, o.Image):
			// ⛔ round-4 review PREV-R4-1: WITH NO MARKER, A RECORD THE EXECUTOR IS NOT ON IS STALE TOO — it was moved
			// outside an update. Where it came from is the record's version: the rule the commit applies itself when a
			// record and a reading differ with no marker (manifest.go CommitManifest), so a run that fails before A-3 and
			// one that moves and is undone record the same `previous`.
			// ⛔ ONLY ON ANOTHER BINARY (round-6 review BIN-1). On the same one — the same DIGEST, never merely the same
			// string (a moving tag, round-7 review R7-1: sameBinary) — a record whose version differs from its reading holds
			// a wrong label, the ARGUS_VERSION override a run before round 6 wrote, never a version the executor came from;
			// taking it for one offered a rollback to the binary running. Under a tag the answer is no previous
			// (pinnedPrevious), never the record's older one.
			o.Previous = pinnedPrevious(in.Installed.Version, in.Installed.Executor, in.Now)
		}
		return o
	}
	if e == nil {
		o := markerOrigin{Previous: in.Installed.Previous}
		if executorKnown(in.Installed.Version) {
			o.Version, o.Image = in.Installed.Version, in.Installed.Executor
		}
		return o
	}
	// ⛔ PREV-4: nothing read under an earlier marker — the executor may be on any version that marker named, and the
	// gate of the NEXT plan must still count them: this run's marker replaces that one
	o := markerOrigin{OneOf: unconfirmedVersions(e)}
	if in.Version != "" && in.Version == e.Version && (in.RollbackTo != "") == (e.RollbackTo != "") && executorKnown(e.FromVersion) {
		o.Version, o.Image, o.Previous = e.FromVersion, e.FromImage, e.FromPrevious
	}
	return o
}

// scriptHelpers are update.sh's own helpers, ported verbatim where the cited line allows.
const scriptHelpers = `
# ⛔ PATH CONVERSION IS OFF FOR docker AND kubectl ONLY. Git Bash rewrites anything shaped like a POSIX
# path in a native program's argv, so ` + "`-v C:/x:/c/x`" + ` reaches docker mangled; update.sh:55 exports the
# switch for the whole script. MEASURED here, that export breaks curl, which is native too: ` + "`-o /dev/null`" + `
# and ` + "`-o /c/…`" + ` fail rc=23 and write nothing. Preflight then captured no Grafana document, and the undo
# would have DELETED live ones. The wrappers leave curl — and the kit's grafana-refs.sh, which relies on
# -o /dev/null — exactly as onboarding runs them.
docker()  { env MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*' docker "$@"; }
kubectl() { env MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*' kubectl "$@"; }
hostpath() { if command -v cygpath >/dev/null 2>&1; then cygpath -m "$1"; else printf '%s' "$1"; fi; }  # update.sh:64

kube() {  # update.sh:295-300
  local a=()
  if [ -n "$KUBECONFIG_ARG" ]; then a+=(--kubeconfig "$(hostpath "$KUBECONFIG_ARG")"); fi
  if [ -n "$KUBE_CONTEXT" ]; then a+=(--context "$KUBE_CONTEXT"); fi
  kubectl "${a[@]}" "$@"
}

dc() {  # update.sh:647-649 — the project's own files, THIS instance's env file, THIS project
  local a=(-f "$(hostpath "$COMPOSE_DIR/docker-compose.yaml")" -f "$(hostpath "$COMPOSE_DIR/docker-compose.byo.yml")")
  if [ -f "$COMPOSE_DIR/docker-compose.byo-m3.yml" ]; then a+=(-f "$(hostpath "$COMPOSE_DIR/docker-compose.byo-m3.yml")"); fi
  a+=(--env-file "$(hostpath "$ENV_FILE")" -p "$PROJECT")
  # ⛔ AC-D55 (#389): --env-file MUST BE THE ONLY SOURCE. Compose gives a variable set in the operator's SHELL
  # priority over the same variable in --env-file, and the runbook has the operator export ARGUS_MCP_IMAGE — so
  # the executor was recreated on the shell's image and /healthz still passed. Every key of env.<id> is removed
  # from THIS call's environment (a subshell: the operator's shell is never touched): the allow-listed keys
  # rendered above (EnvValueAllowed, one source) plus every ARGUS_* key the env file itself carries.
  (
    for k in $UPDATE_SCRUB_KEYS $(grep -oE '^ARGUS_[A-Za-z0-9_]*=' "$ENV_FILE" 2>/dev/null | tr -d '=' || true); do unset -v "$k"; done
    docker compose "${a[@]}" "$@"
  )
}

executor_container() {  # update.sh:375 — found by compose LABELS, never by a guessed container name
  # ⛔ A DOCKER THAT DOES NOT ANSWER IS NOT A MISSING CONTAINER. Measured: a Hyper-V socket timeout made
  # this lookup come back empty and preflight told the operator to onboard an executor that was running.
  # docker's own status is passed up; the caller decides what a failed lookup means.
  local ids
  ids="$(docker ps "$@" -q --filter "label=com.docker.compose.project=$PROJECT" --filter "label=com.docker.compose.service=executor")" || return 1
  printf '%s\n' "$ids" | head -1
}

` + helperUserShell + `

# runner runs the NEWEST image's own verbs, with every path mounted at its own spelling (see above).
# ⛔ AC-D60 (#394): AS THE OPERATOR on Linux (HELPER_USER, above) — the image runs USER root, and on a root
# Docker daemon what it writes into a mount is root-owned on the host: the 0700 files and folders this update
# leaves (undo/, preflight.sh, apply.sh, <router-state>/installed/) would then be unreadable to the operator.
# RUNNER_125: an attempt of the LAST call exited 125 — docker failing around the container, which it can do after
# the verb ran, so whether the verb's effect happened is unknown (apply.sh record_says).
runner() {
  local attempt rc=0
  RUNNER_125=""
  for attempt in 1 2 3; do
    # --mount's explicit src=/dst= carries the identical pair with no colon-splitting to get wrong; MEASURED:
    # the verb inside wrote its file back to the host. ⚠ Rancher Desktop's bind-path translation fails
    # TRANSIENTLY for BOTH forms — "invalid mode" on -v, "mount path must be absolute" on --mount, each
    # exit 125, each succeeding on the next identical call — which is what the retry below absorbs.
    docker run --rm ${HELPER_USER:+--user "$HELPER_USER" -e HOME=/tmp} \
      --mount "type=bind,src=$(hostpath "$KIT"),dst=$KIT" \
      --mount "type=bind,src=$(hostpath "$ROUTER_STATE"),dst=$ROUTER_STATE" \
      --mount "type=bind,src=$(hostpath "$STAGE"),dst=$STAGE" \
      "$RUNNER_IMAGE" "$@" && return 0
    rc=$?
    # 125 is docker failing around the container — never the verb's own answer. Usually it could not START it:
    # Rancher Desktop's bind-path handling returns it transiently, measured here (` + "`invalid mode`" + ` on a spec
    # that worked one call earlier), and onboard.sh:1997-2004 (VR11-O1) retries the same way. ⚠ But it can also
    # come AFTER the verb ran ("Error waiting for container"), so a retry may repeat the verb — safe for the three
    # runner runs: the re-hash rewrites manifest.next.json, a repeated commit reads the record it wrote and records
    # the same, and a repeated report posts the same body again.
    [ "$rc" = 125 ] || return "$rc"
    RUNNER_125=1
    if [ "$attempt" != 3 ]; then printf '   docker exited 125 (it could not start the helper container, or failed around it after it ran) — retrying\n' >&2; sleep $((attempt * 3)); fi
  done
  return "$rc"
}

# report tells the control plane how the attempt ended (C-14). Authenticated with the instance's own
# identity key — the credential /fed/installed already accepts — read inside the container, never here.
report() {  # <outcome> [failed-step]
  runner update report ${CP_URL:+--control-plane "$CP_URL"} --instance-id "$INSTANCE" \
    --router-state "$ROUTER_STATE" --stage "$STAGE" --identity "$COMPOSE_DIR/identity.$INSTANCE.key" \
    --outcome "$1" ${2:+--failed-step "$2"}
}

# report_started tells the control plane this block has BEGUN (AC-D63, #407): the Environments page then says
# "update in progress → <version>" until the final report above ends it. Called once by apply.sh, before the first
# step replaces anything. ⛔ BEST-EFFORT: the caller never lets a failure here stop the update (C-13).
report_started() {
  runner update started ${CP_URL:+--control-plane "$CP_URL"} --instance-id "$INSTANCE" \
    --identity "$COMPOSE_DIR/identity.$INSTANCE.key" --version "${ROLLBACK_TO:-$TARGET_VERSION}" \
    ${ROLLBACK_TO:+--rollback-to "$ROLLBACK_TO"}
}
`

// RenderPreflight writes the script that decides `untouched`.
//
// ⛔ IT IS THE ONLY PRODUCER OF `untouched`, AND IT REPORTS ITSELF (C-14).
func RenderPreflight(p Plan, in PlanInput) string {
	var b strings.Builder
	b.WriteString(scriptHeader)
	b.WriteString(renderLiterals(p, in))
	if in.RouterOnly {
		b.WriteString(preflightRouterOnly)
		return b.String()
	}
	b.WriteString(preflightChecks)
	b.WriteString(preflightTierChecks(in.Tier))
	if in.RollbackTo != "" {
		b.WriteString(preflightRollbackPullable)
	}
	b.WriteString(preflightFence(in.Tier))
	b.WriteString("\nGRAFANA=" + shq(a4Grafana(p, in)) + "\n")
	b.WriteString(preflightCapture)
	return b.String()
}

const preflightChecks = `
fail() {
  # The machine has not been touched. Say the word, tell the control plane, and stop — a preflight
  # that exits quietly looks exactly like an update that was never started (C-14).
  printf 'untouched\n'
  printf '{"instance_id":"%s","image":"%s","generated_at":"%s","ok":false,"failed":"%s"}\n' \
    "$INSTANCE" "$IMAGE_DIGEST" "$GENERATED_AT" "$(printf '%s' "$1" | sed 's/[\\"]/\\&/g')" > "$STAGE/preflight.json" 2>/dev/null || true
  # ⛔ docker run -v CREATES a missing source directory. Reporting from a machine whose kit is gone
  # would conjure an empty kit where the operator's used to be — and it could not authenticate anyway:
  # the identity key lives inside the kit.
  if [ -d "$KIT" ] && [ -d "$STAGE" ] && [ -d "$ROUTER_STATE" ]; then
    report untouched "$1" || true
  else
    printf 'NOT reported to the control plane: the kit, the stage or the router state directory is missing, and the report authenticates with the identity key inside the kit\n' >&2
  fi
  printf 'PREFLIGHT FAILED: %s\n' "$1" >&2
  exit 1
}

[ -d "$KIT" ]          || fail "the kit directory is not there: $KIT"
[ -f "$ENV_FILE" ]     || fail "no env file for this instance: $ENV_FILE"
[ -w "$KIT" ]          || fail "the kit directory is not writable: $KIT"
[ -d "$STAGE" ]        || fail "the staging directory is not there: $STAGE — run 'update plan' first"
[ -d "$STAGE/kit" ]    || fail "no staged kit in $STAGE/kit — run 'update plan' first; A-1 would swap in nothing"
[ -d "$ROUTER_STATE" ] || fail "the router state directory is not there: $ROUTER_STATE — the manifest is written under it"
`

// preflightRollbackPullable refuses a rollback whose target image the host cannot pull.
// discover records the digest of the image a container actually ran from, which proves what WAS
// running — never that the registry still has it today (a retag, a deleted tag, an expired login).
// The same inspect-then-pull idiom the k3d node import already uses (scripts_steps.go) is the check.
const preflightRollbackPullable = `
docker image inspect "$IMAGE_DIGEST" >/dev/null 2>&1 || docker pull "$IMAGE_DIGEST" >/dev/null 2>&1 || \
  fail "the rollback image $IMAGE_DIGEST cannot be pulled onto this machine — nothing was changed. Run docker login if this is a private registry, or re-run discover if this was recorded from a local alias rather than a registry digest"
`

// preflightTierChecks proves the TARGET before anything moves — update.sh:351-367 and :435, as
// refusals that print `untouched` instead of dying after the kit has been renamed.
func preflightTierChecks(tier string) string {
	if tier == "compose" {
		return `
EXEC_ANY="$(executor_container -a)" || fail "docker did not answer while looking for the executor — nothing was changed; re-run once docker responds"
[ -n "$EXEC_ANY" ] || fail "no executor for $INSTANCE: compose project $PROJECT has no executor container — onboard it first (update is not onboarding)"
`
	}
	// kubectl's own words are kept: "NotFound" and "connection refused" need opposite remedies.
	return `
[ -n "$KUBE_CONTEXT" ] || fail "no --kube-context was given — kubectl would act on whichever cluster was selected last (VR6-S1)"
KOUT="$(kube get ns "$NS" -o name 2>&1)" || fail "kubectl could not confirm namespace $NS in '$KUBE_CONTEXT' — nothing was changed: $(printf '%s' "$KOUT" | tr -d '\r' | head -c 300)"
KOUT="$(kube -n "$NS" get deploy executor -o name 2>&1)" || fail "kubectl could not confirm deploy/executor in $NS — nothing was changed: $(printf '%s' "$KOUT" | tr -d '\r' | head -c 300)"
`
}

// preflightFence is the tokenless in-flight check (VR10-U2).
//
// ⛔ THE MATCH IS ON THE VALUE, NOT ON A SPELLING OF THE JSON. The first version matched
// `"running_run_id":""`; `runner-state` prints through json.MarshalIndent (cmd/argus/main.go:59),
// which writes `"running_run_id": ""` WITH a space — so the idle pattern never matched, the busy
// pattern always did, and every idle instance would have been refused as busy. The value is now
// extracted the way update.sh:560 extracts it, which tolerates either spelling.
//
// ⛔ AND A CHECK THAT GOT NO ANSWER IS A FAILED CHECK (V28-001: "do NOT bridge it by treating exit 3 as
// proceed-able"; update.sh:575-588 refuses unverified). The first version proceeded on an empty answer
// as "too old to answer" — and a Hyper-V socket timeout produces exactly that empty answer, so a
// transient docker fault would have waved an update through past a run in flight.
func preflightFence(tier string) string {
	probe := `EXEC_C="$(executor_container)" || fail "docker did not answer while looking for the running executor — nothing was changed; re-run once docker responds"
[ -n "$EXEC_C" ] || fail "the executor of $PROJECT is not running, so whether a run is in flight cannot be asked — a stopped executor is not evidence that none is (update.sh:580-582); start it and re-run"
STATE="$(docker exec "$EXEC_C" argus runner-state 2>&1)" || fail "the executor could not say whether a run is in flight — nothing was changed: $(printf '%s' "$STATE" | tr -d '\r' | head -c 300)"
`
	if tier != "compose" {
		probe = `STATE="$(kube -n "$NS" exec deploy/executor -- argus runner-state 2>&1)" || fail "the executor could not say whether a run is in flight — nothing was changed: $(printf '%s' "$STATE" | tr -d '\r' | head -c 300)"
`
	}
	return `
# ⛔ THE IN-FLIGHT FENCE (VR10-U2). A run in progress is the one state in which moving the executor
# destroys evidence someone is waiting for. READ-ONLY and tokenless by design.
` + probe + `case "$STATE" in
  *'"running_run_id"'*) : ;;
  *) fail "the executor's answer names no running_run_id, so whether a run is in flight is unknown — nothing was changed: $(printf '%s' "$STATE" | tr -d '\r' | head -c 300)" ;;
esac
RUNNING="$(printf '%s\n' "$STATE" | sed -n 's/.*"running_run_id": *"\([^"]*\)".*/\1/p' | head -1 || true)"
[ -z "$RUNNING" ] || fail "run $RUNNING is in flight on this instance — updating now would destroy results not yet reported; wait for it to finish"
printf '  no run in flight (asked the executor)\n'
`
}

// preflightCapture records the live Grafana documents BEFORE anything moves: A-4's undo re-posts
// exactly what was live at this moment, and capturing after A-4 would capture what A-4 wrote.
const preflightCapture = `
mkdir -p "$STAGE/undo"
capture() { # <kind> <url>
  # ⛔ ONLY A 404 IS "ABSENT". The first version wrote {"present":false} on ANY curl failure, so a Grafana
  # that did not answer for a moment (measured) recorded two LIVE documents as absent — and their undo is
  # a DELETE. Now 200 is captured, 404 is absent (INT-039: a real state), and anything else refuses.
  # The body and the code travel on stdout into a file bash opens: curl cannot be trusted with a path.
  local code
  curl -sS --max-time 10 -w '\n%{http_code}' "$2" > "$STAGE/undo/$1.raw" 2>/dev/null || true
  code="$(tail -n 1 "$STAGE/undo/$1.raw" 2>/dev/null || true)"
  case "$code" in ''|*[!0-9]*) code=000 ;; esac
  case "$code" in
    200) sed '$d' "$STAGE/undo/$1.raw" > "$STAGE/undo/$1.json"
         printf '  captured %s\n' "$1" ;;
    404) printf '{"present":false}\n' > "$STAGE/undo/$1.json"
         printf '  %s is not there — its undo will delete what this update creates\n' "$1" ;;
    *)   rm -f "$STAGE/undo/$1.json"
         fail "Grafana answered HTTP $code for this instance's $1, so what is live could not be captured for the undo — nothing was changed; re-run once Grafana answers" ;;
  esac
  rm -f "$STAGE/undo/$1.raw"
}
if [ -n "$GRAFANA" ]; then
  capture dashboard  "$GRAFANA/api/dashboards/uid/argus-overview-$INSTANCE"
  capture datasource "$GRAFANA/api/datasources/uid/loki-$INSTANCE"
fi

printf '{"instance_id":"%s","image":"%s","generated_at":"%s","ok":true}\n' "$INSTANCE" "$IMAGE_DIGEST" "$GENERATED_AT" > "$STAGE/preflight.json"
printf 'preflight ok\n'
`

// preflightRouterOnly is the router-only preflight (C-24). It names no instance, so it reports nothing to
// the control plane — the report authenticates with an INSTANCE's identity key, and there may be none.
const preflightRouterOnly = `
fail() {
  printf 'untouched\n'
  printf '{"instance_id":"","image":"%s","generated_at":"%s","ok":false,"failed":"%s"}\n' \
    "$IMAGE_DIGEST" "$GENERATED_AT" "$(printf '%s' "$1" | sed 's/[\\"]/\\&/g')" > "$STAGE/preflight.json" 2>/dev/null || true
  printf 'PREFLIGHT FAILED: %s\n' "$1" >&2
  exit 1
}
[ -d "$STAGE/kit" ] || fail "no staged kit in $STAGE/kit — run 'update plan --router-only' first"
[ -f "$STAGE/kit/deploy/compose/docker-compose.router.yml" ] || fail "the new kit ships no docker-compose.router.yml — there is no router definition to move to"
[ -f "$STAGE/kit/onboarding/lib/router-version.sh" ] || fail "the new kit ships no onboarding/lib/router-version.sh"
[ -d "$ROUTER_STATE" ] || fail "the router state directory is not there: $ROUTER_STATE — the router would come back with no folder table"
docker version >/dev/null 2>&1 || fail "docker did not answer — nothing was changed; re-run once docker responds"
printf '{"instance_id":"","image":"%s","generated_at":"%s","ok":true}\n' "$IMAGE_DIGEST" "$GENERATED_AT" > "$STAGE/preflight.json"
printf 'preflight ok\n'
`

// a4Grafana is the Grafana A-4 provisions, or "" when A-4 is skipped — so preflight captures an undo
// only for a step that will actually run.
func a4Grafana(p Plan, in PlanInput) string {
	for _, s := range p.Steps {
		if s.ID == "A-4" && s.SkipReason == "" {
			return grafanaURL(in)
		}
	}
	return ""
}

// grafanaURL is onboarding's shared Grafana: onboard.sh:3016 (k3d) and :3183 (compose) both default
// to localhost:3000. The managed tier's is in-cluster and credentialed (SA-D24), so it has none here.
func grafanaURL(in PlanInput) string {
	if in.Tier == "compose" || in.Tier == "k3d" {
		return "http://localhost:3000"
	}
	return ""
}

// shellID turns an A-step id into a shell function suffix. `A-5a` is a legal step id and an illegal
// identifier half.
func shellID(id string) string { return strings.ReplaceAll(id, "-", "_") }
